version: "3.9"

services:
  database:
    image: mariadb:10.8.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    command: --log_warnings=1
    volumes:
    - database:/var/lib/mysql
    ports:
    - 3306:3306

volumes:
  database:
