version: "3.9"

services:
  app:
    build: .
    image: mikelorant/ezdb
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
    - ${PWD}/.ezdb.yaml:/root/.ezdb.yaml
    - ${PWD}/dumps/:/root/dumps/
    - ${HOME}/.ssh:/root/.ssh

  database1:
    image: mariadb:10.8.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    command: --log_warnings=1
    volumes:
    - database1:/var/lib/mysql
    ports:
    - 3306:3306

  database2:
    image: mariadb:10.8.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    command: --log_warnings=1
    volumes:
    - database2:/var/lib/mysql
    ports:
    - 3307:3306

  database3:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
    - database3:/var/lib/postgresql/data
    ports:
    - 5432:5432

  database4:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
    - database4:/var/lib/postgresql/data
    ports:
    - 5433:5432

volumes:
  database1:
  database2:
  database3:
  database4:
